# @format
name: Testing app
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node-setup@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm test
